title: fw6's awesome title
author: fw6
email: lyman.von9506@gmail.com
description: this is a description for this page
# social links
twitter_username: @fefe00383155
github_username: @fw6 

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
